stages:
  - push

variables:
  CONTAINER_VERSION_IMAGE: kiritsu/tetris_from_ci:$CI_BUILD_REF_NAME

push:
  stage: push
  when: on_success
  script:
    - docker build -t $CONTAINER_VERSION_IMAGE .
    - docker push $CONTAINER_VERSION_IMAGE